[package]
name = "ductile"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.4"
chacha20 = "0.4"
rand = "0.7"
failure = "0.1"
bincode = "1.1"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
