name: Rust

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --tests --all -- -D warnings
  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt
        run: cargo fmt --all -- --check
  readme:
    name: Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo install cargo-readme
        run: cargo install cargo-readme
      - name: Rebuild readme
        run: ./tools/update-readme.sh
      - name: Check no changes
        run: |
          git diff --exit-code || (echo 'Readme is outdated!' >&2; exit 1)
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo test
        env:
          RUST_BACKTRACE: 1
        run: cargo test --color=always --all --no-fail-fast
